Shader non broken
AnonymusRaccoon/Bomberman pull request #124
Opened 2021-06-08 14:11 UTC by Octopus773

## Proposed changes

### Add all necessary labels to understand with ease the scope of this pull request

Describe here the big picture of your changes here to communicate to the others members of the group and why we should accept this pull request.

### If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Information
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking changes

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

## Further comments

### If not needed, remove this section
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did
and what alternatives you considered, etc...

2021-06-08 18:21 UTC, Arthi-chaud approved these changes

2021-06-09 07:10 UTC, EternalRat approved these changes

2021-06-09 08:40 UTC, GitBluub approved these changes

2021-06-09 08:51 UTC, AnonymusRaccoon commented on CMakeLists.txt
> -	sources/Models/GameState.hpp
Keep tabs

2021-06-09 08:55 UTC, AnonymusRaccoon commented on lib/Ray/CMakeLists.txt
> +    sources/Shaders/Shaders.cpp sources/Shaders/Shaders.hpp)
Please keep the ')' on a new line, this make simpler merges.

2021-06-09 08:57 UTC, AnonymusRaccoon commented on lib/Ray/sources/Utils/Cache.hpp
> +			if (this->_cache.find(index) != this->_cache.end())
You can use cache.contains(index)

2021-06-09 08:59 UTC, AnonymusRaccoon commented on sources/Component/Shaders/ShaderComponent.hpp
> +		//! @brief efefefefez
Nice documentation

2021-06-09 09:05 UTC, AnonymusRaccoon commented on sources/System/Renderer/RenderSystem.cpp
> +				auto &model = dynamic_cast<RAY::Drawables::Drawables3D::Model &>(*drawable.drawable);
Please store the dynamic casted on a variable, dynamic_cast is costly. Don't do it twice per frame.

2021-06-09 09:07 UTC, AnonymusRaccoon requested changes
Please refrain doing visual changes that does nothing else. It breaks git blame and make merges harder to do.

2021-06-09 14:22 UTC, Arthi-chaud approved these changes

2021-06-09 14:26 UTC, merged