Parser
AnonymusRaccoon/Bomberman pull request #163
Opened 2021-06-14 17:31 UTC by EternalRat

## Proposed changes

We're now able to load and save a game.

Save all entities in the game.
Load a game.

## Information
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Non-breaking changes

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

2021-06-14 21:45 UTC, Octopus773 requested changes

2021-06-14 21:45 UTC, Octopus773 commented on sources/Component/Music/MusicComponent.cpp
> +	float MusicComponent::volume = 0.10;
is this really wanted ?

2021-06-14 21:45 UTC, Octopus773 commented on sources/Parser/ParserYaml.cpp
> +		_player.append("\n  " + name + ":\n    ");
please use std::endl instead of \n on windows std::endl will do \n\r

2021-06-14 21:45 UTC, Octopus773 commented on sources/Parser/ParserYaml.cpp
> +		entity.addComponent<PositionComponent>(pos)
you should create a function createBonus that will be common here and in Map.cpp

2021-06-14 21:45 UTC, Octopus773 commented on sources/Runner/Runner.hpp
> +
Missing doc & should be named mapHeight and mapWidth

2021-06-14 21:49 UTC, Octopus773 reviewed
Here are 3 utility functions that you Should use in the parser

```c++
bool isInteger(const std::string &s)
{
    std::istringstream iss(s);
    int i;

    iss >> std::noskipws >> i;
    return iss.eof() && !iss.fail();
}

bool isFloat(const std::string &s)
{
    std::istringstream iss(s);
    float f;

    iss >> std::noskipws >> f;
    return iss.eof() && !iss.fail();
}

std::vector<std::string> splitStr(const std::string &str, char delim)
{
    std::vector<std::string> strings;
    std::istringstream f(str);
    std::string buffer;

    while (std::getline(f, buffer, delim)) {;
        strings.push_back(buffer);
    }
    return strings;
}
```

2021-06-15 08:08 UTC, AnonymusRaccoon commented on sources/Parser/ParserYaml.cpp
> +				if (entity.getName().find(type.first) != std::string::npos) {
Use ==

2021-06-15 08:35 UTC, AnonymusRaccoon commented on sources/Parser/ParserYaml.cpp
> +			pos.y += 1.0f;
I don't understand.

2021-06-15 08:47 UTC, AnonymusRaccoon commented on sources/Parser/ParserYaml.cpp
> +			y = subStr.substr(x.length(), subStr.find(' '));
this wont work

2021-06-15 08:48 UTC, AnonymusRaccoon commented on sources/Runner/GameScene.cpp
> +			scene->addEntity("Player")
You should display an error message and not use an all catcher like that. If there is an issue with your parser and not with the file, we won't know anything.

2021-06-15 08:50 UTC, AnonymusRaccoon commented
```
bool tryParseInt(const std::string &s, int &i)
{
    std::istringstream iss(s);

    iss >> std::noskipws >> i;
    return iss.eof() && !iss.fail();
}

bool tryParseFloat(const std::string &s, float &f)
{
    std::istringstream iss(s);

    iss >> std::noskipws >> f;
    return iss.eof() && !iss.fail();
}
```

doing this will actually give you a valid parsed int/float if the method return true. This could simply your parsing.

2021-06-16 11:08 UTC, AnonymusRaccoon commented on sources/Runner/PauseMenuScene.cpp
> +	            {
Indentation

2021-06-16 11:08 UTC, AnonymusRaccoon commented on sources/Runner/ResumeLobbyScene.cpp
> +												{
Here too, indentations

2021-06-16 11:13 UTC, AnonymusRaccoon approved these changes

2021-06-16 21:20 UTC, Octopus773 commented
I think the file error should be centered & on error i think i should be in the main menu
![image](https://user-images.githubusercontent.com/56884316/122295363-631dad80-cef9-11eb-890b-66a308575d7d.png)

2021-06-16 21:32 UTC, Octopus773 commented
this is a valid file
```yaml
players:
  Playefzef  zefzefzfzefzefer:
    texture_path: assets/player/textures/blue.png
    max_bomb: 3
    fzufhzeuif ezfefzf speed fezfefzfefzefz: 0.175000
     efzfefzfzef explosion_radius fezfefzefzefzefzefezfzefz: 3.000000
    fezffuijhef efzeffz position: [1.110876 0.000000 11.831073]
  fefPfeziofkeiofjioefjioejfizfezf        jççeçfef   oeilayer:
    texture_path: assets/player/textures/red.png
    max_bomb: 3
    explosion_radius: 10.000000
    speed: 0.150000
    position: [14.869673 0.000000 1.825736]

```
and this is an invalid file
```yaml
players:
  Player:
    texture_path: assets/player/textures/blue.png
    max_bomb: 3
    explosion_radius:         3.000000
    speed: 0.150000
    position: [1.616726 0.000000 16.230330]
  Player:
    texture_path: assets/player/textures/red.png
    max_bomb: 3
    explosion_radius: 3.000000
    speed: 0.150000
    position: [16.000000 0.000000 0.000000]
```

2021-06-17 12:19 UTC, closed without merging